// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://qmwmzevpvnsnidnczafc.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InFtd216ZXZwdm5zbmlkbmN6YWZjIiwicm9sZSI6ImFub24iLCJpYXQiOjE3Mzg5MzM3MTIsImV4cCI6MjA1NDUwOTcxMn0.DXZV0BiD0Z7fUEYargQzl_RCJUXoNr-pZiq7qZfxrBw";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);